# Generated by Django 5.0.6 on 2024-07-31 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumary_all', '0003_location_meetup_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name_plural': 'Location'},
        ),
        migrations.AlterField(
            model_name='meetup',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AddField(
            model_name='meetup',
            name='participant',
            field=models.ManyToManyField(blank=True, null=True, to='sumary_all.participant'),
        ),
    ]
