# Generated by Django 5.0.6 on 2024-07-31 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sumary_all', '0005_meetup_date_meetup_organizer_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetup',
            name='date',
        ),
    ]
