# Generated by Django 5.0.6 on 2024-07-31 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumary_all', '0006_remove_meetup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='date',
            field=models.DateField(default='2005-3-2'),
            preserve_default=False,
        ),
    ]
